[appearance]

[appearance.themes]
system_theme = false
theme = "phenomenon"

[appearance.vertical_tabs]
enabled = false

[appearance.text]
notebook_font_size = 14.0
font_size = 13.0
font_name = "JetBrainsMono Nerd Font"
line_height_ratio = 1.100000023841858

[appearance.window]
zoom_level = 80

[appearance.input]
input_mode = "pinned_to_bottom"

[general]
default_session_mode = "agent"
show_warning_before_quitting = false

[agents]
cloud_conversation_storage_enabled = true

[agents.third_party]
should_render_cli_agent_toolbar = true
auto_open_composer_on_cli_agent_start = true

[agents.warp_agent]
is_any_ai_enabled = false

[agents.warp_agent.other]
show_agent_notifications = true
show_conversation_history = true

[agents.warp_agent.input]
nld_in_terminal_enabled = false

[agents.execution_profiles]

[agents.execution_profiles.default]
apply_code_diffs = "always_ask"
ask_user_question = "always_ask"
autosync_plans_to_warp_drive = true
base_model = "auto-genius"
command_allowlist = []
command_denylist = [
  'bash(\s.*)?',
  'fish(\s.*)?',
  'pwsh(\s.*)?',
  'sh(\s.*)?',
  'zsh(\s.*)?',
  'curl(\s.*)?',
  'eval(\s.*)?',
  'exec(\s.*)?',
  'source(\s.*)?',
  'wget(\s.*)?',
  'dig(\s.*)?',
  'nslookup(\s.*)?',
  'host(\s.*)?',
  'ssh(\s.*)?',
  'scp(\s.*)?',
  'rsync(\s.*)?',
  'telnet(\s.*)?',
  'rm(\s.*)?',
]
computer_use = "never"
directory_allowlist = []
execute_commands = "agent_decides"
mcp_allowlist = []
mcp_denylist = []
mcp_permissions = "agent_decides"
name = "Default"
read_files = "always_allow"
run_agents = "always_ask"
web_search_enabled = true
write_to_pty = "always_ask"

[code]

[code.editor]
show_code_review_button = true
show_project_explorer = true
show_global_search = true

[warp_drive]
enabled = false

[text_editing]
vim_mode_enabled = true

[terminal]

[terminal.input]
input_box_type_setting = "classic"
honor_ps1 = true

[account]
is_settings_sync_enabled = true

[privacy]
telemetry_enabled = true
crash_reporting_enabled = true

[notifications]
toast_duration_secs = 8
